name: 🔂 Surge PR Preview

on:
  pull_request_target:
    types: [labeled]

jobs:
  preview:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'SurgePreview')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: |
            npm install
            npm run doc-demo-build
          dist: docs/example
